import Head from "next/head";
import Header from "@/components/content/Header";
import Footer from "@/components/content/Footer";

export default function AuctionItem() {
  return (
    <>
      <Head>
        <title>ItemName</title>
        <meta name="description" content="Detailed view of Item" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex-col min-h-screen">
        <h1 className="text-white text-6xl">
          Autogenerated content appears here
        </h1>
      </main>
      <Footer />
    </>
  );
}
